"""update_entities_from_erd

Revision ID: 6b1004e70010
Revises: 6cb19ca48ca9
Create Date: 2026-02-22 16:34:31.103378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b1004e70010'
down_revision: Union[str, None] = '6cb19ca48ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('alert_low_balance', sa.Boolean(), nullable=False),
    sa.Column('monthly_reset', sa.Boolean(), nullable=False),
    sa.Column('block_negative_balance', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('category_monthly_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('initial_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('icon', sa.String(length=10), nullable=True))
    op.add_column('categories', sa.Column('initial_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('categories', sa.Column('current_balance', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('categories', sa.Column('reset_month', sa.SmallInteger(), nullable=True))
    op.add_column('categories', sa.Column('reset_year', sa.SmallInteger(), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('categories', 'type')
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('transactions', 'date')
    op.drop_column('transactions', 'type')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('transactions', sa.Column('type', postgresql.ENUM('income', 'expense', name='transactiontype'), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('transactions', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('categories', sa.Column('type', postgresql.ENUM('income', 'expense', name='categorytype'), autoincrement=False, nullable=False))
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'reset_year')
    op.drop_column('categories', 'reset_month')
    op.drop_column('categories', 'current_balance')
    op.drop_column('categories', 'initial_amount')
    op.drop_column('categories', 'icon')
    op.drop_table('category_monthly_snapshots')
    op.drop_table('user_settings')
    op.drop_table('login_tokens')
    # ### end Alembic commands ###
